=== DankoDmitriy/task2/src/main/resources/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="urn:com.danko.greenhouse"
        xmlns:tns="urn:com.danko.greenhouse"
        elementFormDefault="qualified">

    <element name="flowers" type="tns:Flowers"/>
    <element name="flower" type="tns:Flower"/>
    <element name="cut-flower" type="tns:CutFlower" substitutionGroup="tns:flower"/>
    <element name="exotic-flower" type="tns:ExoticFlower" substitutionGroup="tns:flower"/>

    <complexType name="Flowers">
        <sequence>
            <element ref="tns:flower" minOccurs="2" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Flower" abstract="true">
        <sequence>
            <element name="title" type="tns:Title"/>
            <element name="origin" type="tns:Origin"/>
            <element name="leaf-color" type="tns:Color"/>
        </sequence>
        <attribute name="vendor-code" type="tns:VendorCode" use="required"/>
        <attribute name="planting-date" type="date" use="required"/>
    </complexType>

    <complexType name="CutFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="stem-length" type="tns:StemLength"/>
                    <element name="bud-color" type="tns:Color"/>
                    <element name="temperature-cut" type="tns:TemperatureCut"/>
                </sequence>
                <attribute name="cut-date" type="date" use="required"/>
                <attribute name="poisonous" type="boolean" use="optional" default="false"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="ExoticFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="soil" type="tns:Soil"/>
                    <element name="multiplying" type="tns:Multiplying"/>
                    <element name="watering" type="tns:Watering"/>
                    <element name="temperature-exotic-flower" type="tns:TemperatureExoticFlower"/>
                    <element name="photophilous" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="TemperatureExoticFlower">
        <restriction base="double">
            <minExclusive value="28"/>
            <maxExclusive value="35"/>
        </restriction>
    </simpleType>

    <simpleType name="Watering">
        <restriction base="int">
            <minExclusive value="100"/>
            <maxExclusive value="1500"/>
        </restriction>
    </simpleType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="Leaf"/>
            <enumeration value="Seed"/>
            <enumeration value="Stalk"/>
        </restriction>
    </simpleType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="Limestone"/>
            <enumeration value="Turfy"/>
            <enumeration value="Humus"/>
        </restriction>
    </simpleType>

    <simpleType name="TemperatureCut">
        <restriction base="double">
            <minExclusive value="3"/>
            <maxExclusive value="14"/>
        </restriction>
    </simpleType>

    <simpleType name="StemLength">
        <restriction base="double">
            <minExclusive value="1"/>
            <maxExclusive value="100"/>
        </restriction>
    </simpleType>

    <simpleType name="Title">
        <restriction base="string">
            <pattern value="[a-zA-Z ]{2,50}"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <enumeration value="South_America"/>
            <enumeration value="North_America"/>
            <enumeration value="Africa"/>
            <enumeration value="Australia"/>
            <enumeration value="Europe"/>
            <enumeration value="Asia"/>
        </restriction>
    </simpleType>

    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="White"/>
            <enumeration value="Red"/>
            <enumeration value="Green"/>
            <enumeration value="Blue"/>
            <enumeration value="Yellow"/>
            <enumeration value="Orange"/>
        </restriction>
    </simpleType>

    <simpleType name="VendorCode">
        <restriction base="ID">
            <pattern value="\p{Upper}\d{4}"/>
        </restriction>
    </simpleType>

</schema>

=== DankoDmitriy/task2/test_data/flowers_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:com.danko.greenhouse"
         xsi:schemaLocation="urn:com.danko.greenhouse schema.xsd">
    <cut-flower vendor-code="C0001" planting-date="2020-10-01" cut-date="2021-06-01" poisonous="true">
        <title>African lily of the valley</title>
        <origin>Africa</origin>
        <leaf-color>Green</leaf-color>
        <stem-length>16</stem-length>
        <bud-color>White</bud-color>
        <temperature-cut>8</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0002" planting-date="2019-10-01" cut-date="2021-06-03">
        <title>Lily of the valley European</title>
        <origin>Europe</origin>
        <leaf-color>Orange</leaf-color>
        <stem-length>6</stem-length>
        <bud-color>Red</bud-color>
        <temperature-cut>12</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0003" planting-date="2019-10-01" cut-date="2021-06-03" poisonous="true">
        <title>Lily of the valley asian red</title>
        <origin>Asia</origin>
        <leaf-color>Yellow</leaf-color>
        <stem-length>10</stem-length>
        <bud-color>Red</bud-color>
        <temperature-cut>9</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0004" planting-date="2020-01-01" cut-date="2021-03-08">
        <title>Lily of the valley australian blue</title>
        <origin>Australia</origin>
        <leaf-color>Blue</leaf-color>
        <stem-length>12</stem-length>
        <bud-color>Blue</bud-color>
        <temperature-cut>11</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0005" planting-date="2020-02-01" cut-date="2021-03-08">
        <title>Lily of the Valley South American White</title>
        <origin>South_America</origin>
        <leaf-color>White</leaf-color>
        <stem-length>17</stem-length>
        <bud-color>White</bud-color>
        <temperature-cut>10</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0006" planting-date="2020-02-01" cut-date="2021-03-08">
        <title>Lily of the Valley South American Red</title>
        <origin>South_America</origin>
        <leaf-color>Red</leaf-color>
        <stem-length>17</stem-length>
        <bud-color>White</bud-color>
        <temperature-cut>13</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0007" planting-date="2020-02-01" cut-date="2021-03-08">
        <title>Lily of the Valley South American Blue</title>
        <origin>South_America</origin>
        <leaf-color>Green</leaf-color>
        <stem-length>17</stem-length>
        <bud-color>Blue</bud-color>
        <temperature-cut>13</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0008" planting-date="2020-02-01" cut-date="2021-03-08">
        <title>Lily of the Valley South American Yellow</title>
        <origin>South_America</origin>
        <leaf-color>Yellow</leaf-color>
        <stem-length>17</stem-length>
        <bud-color>White</bud-color>
        <temperature-cut>13</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0009" planting-date="2020-02-01" cut-date="2021-03-08">
        <title>Lily of the Valley Asia Yellow</title>
        <origin>Asia</origin>
        <leaf-color>Yellow</leaf-color>
        <stem-length>17</stem-length>
        <bud-color>White</bud-color>
        <temperature-cut>13</temperature-cut>
    </cut-flower>
    <cut-flower vendor-code="C0010" planting-date="2020-02-01" cut-date="2021-03-08">
        <title>Lily of the Valley Asia Red</title>
        <origin>Asia</origin>
        <leaf-color>Red</leaf-color>
        <stem-length>32</stem-length>
        <bud-color>White</bud-color>
        <temperature-cut>13</temperature-cut>
    </cut-flower>
    <exotic-flower vendor-code="E0001" planting-date="2015-01-01">
        <title>North American rose</title>
        <origin>North_America</origin>
        <leaf-color>Blue</leaf-color>
        <soil>Turfy</soil>
        <multiplying>Stalk</multiplying>
        <watering>389</watering>
        <temperature-exotic-flower>33</temperature-exotic-flower>
        <photophilous>true</photophilous>
    </exotic-flower>
    <exotic-flower vendor-code="E0002" planting-date="2018-01-01">
        <title>South America rose</title>
        <origin>South_America</origin>
        <leaf-color>Yellow</leaf-color>
        <soil>Humus</soil>
        <multiplying>Leaf</multiplying>
        <watering>678</watering>
        <temperature-exotic-flower>29</temperature-exotic-flower>
        <photophilous>false</photophilous>
    </exotic-flower>
    <exotic-flower vendor-code="E0003" planting-date="2011-01-01">
        <title>Asia rose Blue</title>
        <origin>Asia</origin>
        <leaf-color>Green</leaf-color>
        <soil>Limestone</soil>
        <multiplying>Seed</multiplying>
        <watering>991</watering>
        <temperature-exotic-flower>34</temperature-exotic-flower>
        <photophilous>true</photophilous>
    </exotic-flower>
    <exotic-flower vendor-code="E0004" planting-date="2017-01-01">
        <title>Australia rose Yellow</title>
        <origin>Australia</origin>
        <leaf-color>Green</leaf-color>
        <soil>Turfy</soil>
        <multiplying>Leaf</multiplying>
        <watering>190</watering>
        <temperature-exotic-flower>29</temperature-exotic-flower>
        <photophilous>true</photophilous>
    </exotic-flower>
    <exotic-flower vendor-code="E0005" planting-date="2014-01-01">
        <title>Europe rose Red</title>
        <origin>Europe</origin>
        <leaf-color>Red</leaf-color>
        <soil>Limestone</soil>
        <multiplying>Seed</multiplying>
        <watering>530</watering>
        <temperature-exotic-flower>29</temperature-exotic-flower>
        <photophilous>true</photophilous>
    </exotic-flower>
    <exotic-flower vendor-code="E0006" planting-date="2021-01-01">
        <title>Australia rose Blue</title>
        <origin>Australia</origin>
        <leaf-color>Blue</leaf-color>
        <soil>Turfy</soil>
        <multiplying>Stalk</multiplying>
        <watering>1400</watering>
        <temperature-exotic-flower>29</temperature-exotic-flower>
        <photophilous>false</photophilous>
    </exotic-flower>
</flowers>
